# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: circuits

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest  # ubuntu-18.04  # ubuntu-latest doesn't work with 3.4

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          # - 'pypy2'  # FIXME: flaky
          # - 'pypy3'  # FIXME: flaky

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U isort flake8 pytest
        pip install setuptools-scm==5.0.2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Lint with isort
      run: |
        isort . --check --diff || true
      continue-on-error: true
    - name: Install test requirements
      run: |
        pip install -Ur requirements-test.txt
        pip install -Ue .
    - name: Test with pytest
      run: |
        tox -e py -- --tb=native -vvv -l --cov --no-cov-on-fail --cov-report=
